#config.yaml
hyperparameters:
        batch_size: 100
        lr: 1e-3
        epochs: 25
        seed: 69
        cuda: True
        train_data_path: '../../../data/processed/train.pickle'
        model_out_path: '../../../models/'
